class Pyop3Exception(Exception):
    pass


class DataValueError(ValueError, Pyop3Exception):
    pass
